### ISSUE TITLE
lerna bootstrap failes - Not found : @tecla5/gql-auth

### ISSUE THREAD

**Issue by dennisbrandenberger** [kristianmandrup/gc-auth0#1]
This is the result (I ran the comman from gc-auth0 root)
```
$ lerna bootstrap
lerna info version 2.0.0-rc.5
lerna info Bootstrapping 11 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna ERR! execute Error: Command failed: npm install
lerna ERR! execute npm ERR! Darwin 16.5.0
lerna ERR! execute npm ERR! argv "/Users/kjetilge/.nvm/versions/node/v7.10.0/bin/node" "/Users/kjetilge/.nvm/versions/node/v7.10.0/bin/npm" "install"
lerna ERR! execute npm ERR! node v7.10.0
lerna ERR! execute npm ERR! npm  v4.2.0
lerna ERR! execute npm ERR! code E404
lerna ERR! execute 
lerna ERR! execute npm ERR! 404 Not found : @tecla5/gql-auth
lerna ERR! execute npm ERR! 404 
lerna ERR! execute npm ERR! 404  '@tecla5/gql-auth' is not in the npm registry.
lerna ERR! execute npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
lerna ERR! execute npm ERR! 404 
lerna ERR! execute npm ERR! 404 Note that you can also install from a
lerna ERR! execute npm ERR! 404 tarball, folder, http url, or git url.
lerna ERR! execute 
lerna ERR! execute npm ERR! Please include the following file with any support request:
lerna ERR! execute npm ERR!     /Users/kjetilge/.npm/_logs/2017-06-02T19_15_06_100Z-debug.log
lerna ERR! execute 
lerna ERR! execute     at Promise.all.then.arr (/Users/kjetilge/.nvm/versions/node/v7.10.0/lib/node_modules/lerna/node_modules/execa/index.js:210:11)
lerna ERR! execute     at process._tickCallback (internal/process/next_tick.js:109:7)
lerna ERR! execute  callback with error
lerna ERR! execute  { Error: Command failed: npm install
lerna ERR! execute npm ERR! Darwin 16.5.0
lerna ERR! execute npm ERR! argv "/Users/kjetilge/.nvm/versions/node/v7.10.0/bin/node" "/Users/kjetilge/.nvm/versions/node/v7.10.0/bin/npm" "install"
lerna ERR! execute npm ERR! node v7.10.0
lerna ERR! execute npm ERR! npm  v4.2.0
lerna ERR! execute npm ERR! code E404
lerna ERR! execute 
lerna ERR! execute npm ERR! 404 Not found : @tecla5/gql-auth
lerna ERR! execute npm ERR! 404 
lerna ERR! execute npm ERR! 404  '@tecla5/gql-auth' is not in the npm registry.
lerna ERR! execute npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
lerna ERR! execute npm ERR! 404 
lerna ERR! execute npm ERR! 404 Note that you can also install from a
lerna ERR! execute npm ERR! 404 tarball, folder, http url, or git url.
lerna ERR! execute 
lerna ERR! execute npm ERR! Please include the following file with any support request:
lerna ERR! execute npm ERR!     /Users/kjetilge/.npm/_logs/2017-06-02T19_15_06_100Z-debug.log
lerna ERR! execute 
lerna ERR! execute     at Promise.all.then.arr (/Users/kjetilge/.nvm/versions/node/v7.10.0/lib/node_modules/lerna/node_modules/execa/index.js:210:11)
lerna ERR! execute     at process._tickCallback (internal/process/next_tick.js:109:7)
lerna ERR! execute   code: 1,
lerna ERR! execute   killed: false,
lerna ERR! execute   stdout: '',
lerna ERR! execute   stderr: 'npm ERR! Darwin 16.5.0\nnpm ERR! argv "/Users/kjetilge/.nvm/versions/node/v7.10.0/bin/node" "/Users/kjetilge/.nvm/versions/node/v7.10.0/bin/npm" "install"\nnpm ERR! node v7.10.0\nnpm ERR! npm  v4.2.0\nnpm ERR! code E404\n\nnpm ERR! 404 Not found : @tecla5/gql-auth\nnpm ERR! 404 \nnpm ERR! 404  \'@tecla5/gql-auth\' is not in the npm registry.\nnpm ERR! 404 You should bug the author to publish it (or use the name yourself!)\nnpm ERR! 404 \nnpm ERR! 404 Note that you can also install from a\nnpm ERR! 404 tarball, folder, http url, or git url.\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     /Users/kjetilge/.npm/_logs/2017-06-02T19_15_06_100Z-debug.log\n',
lerna ERR! execute   failed: true,
lerna ERR! execute   signal: null,
lerna ERR! execute   cmd: 'npm install',
lerna ERR! execute   timedOut: false }
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
(node:2009) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Command failed: npm install
npm ERR! Darwin 16.5.0
npm ERR! argv "/Users/kjetilge/.nvm/versions/node/v7.10.0/bin/node" "/Users/kjetilge/.nvm/versions/node/v7.10.0/bin/npm" "install"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code E404

npm ERR! 404 Not found : @tecla5/gql-auth
npm ERR! 404 
npm ERR! 404  '@tecla5/gql-auth' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kjetilge/.npm/_logs/2017-06-02T19_15_06_100Z-debug.log

(node:2009) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kristianmandrup** [comment]
Been refactoring a lot lately and renaming packages. Simply a package naming​ mismatch. Will fix this weekend.

**Comment by kristianmandrup** [comment]
Fixed. Project still under development... Most welcome to try it out, help improve it etc.

**Comment by kristianmandrup** [comment]
Did some work on it this morning. Almost there. Just some minor issues with webpack/babel compile needed to be sorted out... If you are good at this shit, please give it a try.
